import type { Seafarer } from "@/lib/seafarers";

export const SEAFARERS: Seafarer[] = [
  /* ── Page 1 originals ───────────────────────────────── */
  {
    id: "S0000099", firstName: "Arthur",   lastName: "Simmons",
    rank: "Second Engineer", nationality: "Bulgarian", status: "Onboard",
    dateOfBirth: "12 Mar 1989", placeOfBirth: "Varna, Bulgaria",
    vesselType: "Bulk carrier", lastVessel: "MSC Stella", currentVessel: "ZIM Atlantic", nextVessel: "MSC Aurora",
    availableFrom: "15 Aug 2026", assignmentDate: "26 Apr 2026", agent: "Polishmar Manning",
    airport: "VAR — Varna", salary: 4850, age: 36, promotions: 2, performanceScore: 87,
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=560&fit=crop&q=80",
  },
  {
    id: "S0000112", firstName: "Elena",    lastName: "Vasquez",
    rank: "Chief Officer", nationality: "Filipino", status: "Available",
    dateOfBirth: "05 Jul 1985", placeOfBirth: "Manila, Philippines",
    vesselType: "Container ship", lastVessel: "CMA CGM Liberty", nextVessel: "Ever Given II",
    availableFrom: "01 Jun 2026", assignmentDate: "01 Jun 2026", agent: "Maersk Manning",
    email: "e.vasquez@example.com", phone: "+63 912 345 6789",
    airport: "MNL — Manila Ninoy Aquino", salary: 6200, age: 40, promotions: 3, performanceScore: 92,
    photo: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400&h=560&fit=crop&q=80",
  },
  {
    id: "S0000078", firstName: "Dmitri",   lastName: "Volkov",
    rank: "Master", nationality: "Russian", status: "On leave",
    dateOfBirth: "22 Feb 1975", placeOfBirth: "St. Petersburg, Russia",
    vesselType: "Tanker", lastVessel: "Orion Spirit", nextVessel: "Nordic Eagle",
    availableFrom: "10 Sep 2026", assignmentDate: "10 Sep 2026", agent: "Sovcomflot Agency",
    email: "d.volkov@example.com",
    airport: "LED — St. Petersburg Pulkovo", salary: 9800, age: 50, promotions: 5, performanceScore: 94,
    photo: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=560&fit=crop&q=80",
  },
  {
    id: "S0000145", firstName: "James",    lastName: "Okafor",
    rank: "AB Seaman", nationality: "Nigerian", status: "Onboard",
    dateOfBirth: "14 Nov 1998", placeOfBirth: "Lagos, Nigeria",
    vesselType: "Bulk carrier", lastVessel: "Pacific Horizon", currentVessel: "Atlantic Pioneer",
    availableFrom: "20 Oct 2026", assignmentDate: "20 Apr 2026", agent: "Stolt Manning",
    airport: "LOS — Lagos Murtala Muhammed", salary: 1850, age: 27, promotions: 0, performanceScore: 78,
  },
  {
    id: "S0000061", firstName: "Maria",    lastName: "Santos",
    rank: "Chief Cook", nationality: "Filipino", status: "Training",
    dateOfBirth: "30 Aug 1990", placeOfBirth: "Cebu City, Philippines",
    vesselType: "Cruise ship", lastVessel: "Diamond Princess", nextVessel: "Symphony of the Seas",
    availableFrom: "15 Jul 2026", assignmentDate: "15 Jul 2026", agent: "V.Ships Leisure",
    email: "m.santos@example.com", phone: "+63 917 654 3210",
    airport: "CEB — Cebu Mactan", salary: 2400, age: 35, promotions: 1, performanceScore: 88,
  },
  {
    id: "S0000203", firstName: "Nikos",    lastName: "Papadopoulos",
    rank: "Chief Engineer", nationality: "Greek", status: "Available",
    dateOfBirth: "18 Jan 1980", placeOfBirth: "Piraeus, Greece",
    vesselType: "VLCC Tanker", lastVessel: "Hercules Titan", nextVessel: "Poseidon Glory",
    availableFrom: "01 Jun 2026", assignmentDate: "01 Jun 2026", agent: "Angelakos Manning",
    email: "n.papadopoulos@example.com",
    airport: "ATH — Athens Eleftherios Venizelos", salary: 8500, age: 45, promotions: 4, performanceScore: 91,
    photo: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=400&h=560&fit=crop&q=80",
  },
  {
    id: "S0000187", firstName: "Yuki",     lastName: "Tanaka",
    rank: "Second Officer", nationality: "Japanese", status: "Onboard",
    dateOfBirth: "03 Apr 1993", placeOfBirth: "Yokohama, Japan",
    vesselType: "Car carrier", lastVessel: "Euphony Ace", currentVessel: "Courageous Leader", nextVessel: "Trans Future 7",
    availableFrom: "30 Nov 2026", assignmentDate: "30 May 2026", agent: "NYK Shipmanagement",
    email: "y.tanaka@example.com", phone: "+81 45 123 4567",
    airport: "HND — Tokyo Haneda", salary: 5100, age: 32, promotions: 1, performanceScore: 85,
    photo: "https://images.unsplash.com/photo-1556157382-97eda2d62296?w=400&h=560&fit=crop&q=80",
  },
  {
    id: "S0000254", firstName: "Carlos",   lastName: "Reyes",
    rank: "Bosun", nationality: "Colombian", status: "On leave",
    dateOfBirth: "25 Jun 1987", placeOfBirth: "Cartagena, Colombia",
    vesselType: "Container ship", lastVessel: "MSC Ambra", nextVessel: "MSC Ambra",
    availableFrom: "05 Aug 2026", assignmentDate: "05 Aug 2026", agent: "Navesco S.A.",
    phone: "+57 315 987 6543",
    airport: "CTG — Cartagena Rafael Núñez", salary: 2200, age: 38, promotions: 1, performanceScore: 82,
  },

  /* ── Page 2 ─────────────────────────────────────────── */
  {
    id: "S0000300", firstName: "Andrei",   lastName: "Popescu",
    rank: "Third Engineer", nationality: "Romanian", status: "Available",
    dateOfBirth: "07 Sep 1991", placeOfBirth: "Constanța, Romania",
    vesselType: "Chemical tanker", lastVessel: "Baltic Chemist", nextVessel: "Stolt Egret",
    availableFrom: "10 Jun 2026", assignmentDate: "10 Jun 2026", agent: "Anglo-Eastern Romania",
    airport: "CND — Constanța", salary: 3900, age: 34, promotions: 1, performanceScore: 83,
  },
  {
    id: "S0000301", firstName: "Ivan",     lastName: "Kovalenko",
    rank: "Master", nationality: "Ukrainian", status: "On leave",
    dateOfBirth: "14 Mar 1971", placeOfBirth: "Odessa, Ukraine",
    vesselType: "General cargo", lastVessel: "UKR Trader", nextVessel: "Black Sea Pioneer",
    availableFrom: "01 Jul 2026", assignmentDate: "01 Jul 2026", agent: "Marlow Navigation",
    email: "i.kovalenko@example.com",
    airport: "ODS — Odessa", salary: 8900, age: 54, promotions: 6, performanceScore: 96,
    photo: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=560&fit=crop&q=80",
  },
  {
    id: "S0000302", firstName: "Priya",    lastName: "Sharma",
    rank: "Chief Officer", nationality: "Indian", status: "Onboard",
    dateOfBirth: "22 Oct 1988", placeOfBirth: "Mumbai, India",
    vesselType: "Container ship", lastVessel: "APL Denver", currentVessel: "MSC Gülsün",
    availableFrom: "15 Dec 2026", assignmentDate: "15 Jun 2026", agent: "V.Ships India",
    email: "p.sharma@example.com", phone: "+91 98765 43210",
    airport: "BOM — Mumbai Chhatrapati Shivaji", salary: 6800, age: 36, promotions: 3, performanceScore: 90,
    photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=560&fit=crop&q=80",
  },
  {
    id: "S0000303", firstName: "Lasse",    lastName: "Eriksen",
    rank: "Chief Engineer", nationality: "Norwegian", status: "Available",
    dateOfBirth: "30 May 1977", placeOfBirth: "Bergen, Norway",
    vesselType: "Offshore vessel", lastVessel: "Island Frontier", nextVessel: "Skandi Buchan",
    availableFrom: "01 Jun 2026", assignmentDate: "01 Jun 2026", agent: "Wilhelmsen Ship Management",
    email: "l.eriksen@example.com",
    airport: "BGO — Bergen Flesland", salary: 11200, age: 48, promotions: 5, performanceScore: 95,
    photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=560&fit=crop&q=80",
  },
  {
    id: "S0000304", firstName: "Wei",      lastName: "Chen",
    rank: "AB Seaman", nationality: "Chinese", status: "Onboard",
    dateOfBirth: "11 Jan 2000", placeOfBirth: "Shanghai, China",
    vesselType: "Bulk carrier", lastVessel: "Ocean Bulker", currentVessel: "Jin Hai Hui",
    availableFrom: "05 Nov 2026", assignmentDate: "05 May 2026", agent: "COSCO Shipping Manning",
    airport: "PVG — Shanghai Pudong", salary: 1700, age: 25, promotions: 0, performanceScore: 74,
  },
  {
    id: "S0000305", firstName: "Jose",     lastName: "Mendoza",
    rank: "Pumpman", nationality: "Filipino", status: "Onboard",
    dateOfBirth: "18 Feb 1986", placeOfBirth: "Iloilo City, Philippines",
    vesselType: "VLCC Tanker", lastVessel: "Mayon Spirit", currentVessel: "TI Europe",
    availableFrom: "10 Oct 2026", assignmentDate: "10 Apr 2026", agent: "Maersk Manning",
    phone: "+63 919 876 5432",
    airport: "ILO — Iloilo", salary: 2800, age: 39, promotions: 2, performanceScore: 86,
  },
  {
    id: "S0000306", firstName: "Sarah",    lastName: "Mitchell",
    rank: "Third Officer", nationality: "British", status: "Available",
    dateOfBirth: "09 Dec 1995", placeOfBirth: "Southampton, United Kingdom",
    vesselType: "Cruise ship", lastVessel: "Britannia", nextVessel: "Iona",
    availableFrom: "20 Jun 2026", assignmentDate: "20 Jun 2026", agent: "P&O Cruises Manning",
    email: "s.mitchell@example.com",
    airport: "LHR — London Heathrow", salary: 4200, age: 30, promotions: 1, performanceScore: 87,
    photo: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=560&fit=crop&q=80",
  },
  {
    id: "S0000307", firstName: "Mahmoud",  lastName: "Hassan",
    rank: "Motorman", nationality: "Egyptian", status: "Onboard",
    dateOfBirth: "03 Jul 1985", placeOfBirth: "Alexandria, Egypt",
    vesselType: "Ro-Ro", lastVessel: "Arabia", currentVessel: "Viking Constanza",
    availableFrom: "01 Dec 2026", assignmentDate: "01 Jun 2026", agent: "Arab Maritime Petroleum",
    airport: "ALY — Alexandria El Nozha", salary: 2100, age: 40, promotions: 1, performanceScore: 79,
  },

  /* ── Page 3 ─────────────────────────────────────────── */
  {
    id: "S0000308", firstName: "Ana",      lastName: "Lima",
    rank: "Chief Cook", nationality: "Brazilian", status: "Available",
    dateOfBirth: "27 Mar 1984", placeOfBirth: "Santos, Brazil",
    vesselType: "Container ship", lastVessel: "Hamburg Süd Rio", nextVessel: "Santa Isabel",
    availableFrom: "01 Jul 2026", assignmentDate: "01 Jul 2026", agent: "Hapag-Lloyd Brazil",
    email: "a.lima@example.com",
    airport: "GRU — São Paulo Guarulhos", salary: 2600, age: 41, promotions: 2, performanceScore: 89,
  },
  {
    id: "S0000309", firstName: "Pawel",    lastName: "Kowalski",
    rank: "Bosun", nationality: "Polish", status: "Training",
    dateOfBirth: "15 Aug 1992", placeOfBirth: "Gdańsk, Poland",
    vesselType: "Bulk carrier", lastVessel: "Polsteam Wisdom",
    availableFrom: "01 Sep 2026", assignmentDate: "01 Sep 2026", agent: "Polsteam Manning",
    airport: "GDN — Gdańsk Lech Wałęsa", salary: 2500, age: 33, promotions: 1, performanceScore: 81,
  },
  {
    id: "S0000310", firstName: "Tariq",    lastName: "Abdullah",
    rank: "Fourth Engineer", nationality: "Bangladeshi", status: "Onboard",
    dateOfBirth: "20 Nov 1996", placeOfBirth: "Chittagong, Bangladesh",
    vesselType: "General cargo", lastVessel: "BSC Padma", currentVessel: "MV Meghna",
    availableFrom: "15 Nov 2026", assignmentDate: "15 May 2026", agent: "BSM Bangladesh",
    airport: "CGP — Chittagong", salary: 2200, age: 29, promotions: 0, performanceScore: 76,
  },
  {
    id: "S0000311", firstName: "Ingrid",   lastName: "Hansen",
    rank: "Second Officer", nationality: "Norwegian", status: "On leave",
    dateOfBirth: "06 Feb 1990", placeOfBirth: "Oslo, Norway",
    vesselType: "Offshore vessel", lastVessel: "Siem Spearfish", nextVessel: "Siem Sword",
    availableFrom: "15 Aug 2026", assignmentDate: "15 Aug 2026", agent: "Siem Offshore",
    email: "i.hansen@example.com",
    airport: "OSL — Oslo Gardermoen", salary: 6400, age: 35, promotions: 2, performanceScore: 88,
  },
  {
    id: "S0000312", firstName: "Samuel",   lastName: "Asante",
    rank: "OS", nationality: "Ghanaian", status: "Available",
    dateOfBirth: "12 Apr 2001", placeOfBirth: "Tema, Ghana",
    vesselType: "Bulk carrier", lastVessel: "Ghana Star",
    availableFrom: "01 Jun 2026", assignmentDate: "01 Jun 2026", agent: "Stolt Manning",
    airport: "ACC — Accra Kotoka", salary: 1500, age: 24, promotions: 0, performanceScore: 72,
  },
  {
    id: "S0000313", firstName: "Reza",     lastName: "Karimi",
    rank: "Third Engineer", nationality: "Iranian", status: "Onboard",
    dateOfBirth: "17 Sep 1989", placeOfBirth: "Bandar Abbas, Iran",
    vesselType: "Chemical tanker", lastVessel: "Persian Gulf Carrier", currentVessel: "Stolt Osprey",
    availableFrom: "20 Sep 2026", assignmentDate: "20 Mar 2026", agent: "Anglo-Eastern",
    airport: "BND — Bandar Abbas", salary: 3700, age: 36, promotions: 1, performanceScore: 84,
  },
  {
    id: "S0000314", firstName: "Marina",   lastName: "Sokolova",
    rank: "Chief Officer", nationality: "Russian", status: "Available",
    dateOfBirth: "28 Dec 1983", placeOfBirth: "Novorossiysk, Russia",
    vesselType: "Tanker", lastVessel: "Primorsk", nextVessel: "Ligovsky",
    availableFrom: "15 Jun 2026", assignmentDate: "15 Jun 2026", agent: "Sovcomflot Agency",
    email: "m.sokolova@example.com",
    airport: "GDZ — Anapa", salary: 7100, age: 42, promotions: 3, performanceScore: 92,
    photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=560&fit=crop&q=80",
  },
  {
    id: "S0000315", firstName: "Hamid",    lastName: "Malik",
    rank: "AB Seaman", nationality: "Pakistani", status: "Onboard",
    dateOfBirth: "05 Oct 1993", placeOfBirth: "Karachi, Pakistan",
    vesselType: "Container ship", lastVessel: "CSCL Pacific Ocean", currentVessel: "COSCO Shipping Scorpio",
    availableFrom: "10 Oct 2026", assignmentDate: "10 Apr 2026", agent: "COSCO Shipping Manning",
    airport: "KHI — Karachi Jinnah", salary: 1750, age: 32, promotions: 0, performanceScore: 77,
  },
  {
    id: "S0000316", firstName: "Jin-Ho",   lastName: "Park",
    rank: "Second Engineer", nationality: "South Korean", status: "Training",
    dateOfBirth: "14 Jun 1988", placeOfBirth: "Busan, South Korea",
    vesselType: "Car carrier", lastVessel: "Hyundai No. 105",
    availableFrom: "01 Aug 2026", assignmentDate: "01 Aug 2026", agent: "Hyundai Glovis Manning",
    email: "jh.park@example.com",
    airport: "PUS — Busan Gimhae", salary: 5400, age: 37, promotions: 2, performanceScore: 86,
  },
  {
    id: "S0000317", firstName: "Isabella", lastName: "Romano",
    rank: "Deck Cadet", nationality: "Italian", status: "Available",
    dateOfBirth: "03 Feb 2003", placeOfBirth: "Genoa, Italy",
    vesselType: "Container ship", lastVessel: "MSC Caterina",
    availableFrom: "01 Jun 2026", assignmentDate: "01 Jun 2026", agent: "MSC Crew Management",
    email: "i.romano@example.com",
    airport: "GOA — Genoa Cristoforo Colombo", salary: 1200, age: 23, promotions: 0, performanceScore: 80,
  },
  {
    id: "S0000318", firstName: "Tomasz",   lastName: "Wieczorek",
    rank: "Chief Engineer", nationality: "Polish", status: "On leave",
    dateOfBirth: "22 Jul 1972", placeOfBirth: "Szczecin, Poland",
    vesselType: "Ro-Ro", lastVessel: "Finlandia", nextVessel: "Finnkraft",
    availableFrom: "01 Oct 2026", assignmentDate: "01 Oct 2026", agent: "Finnlines Manning",
    email: "t.wieczorek@example.com",
    airport: "SZZ — Szczecin Goleniów", salary: 9200, age: 53, promotions: 5, performanceScore: 93,
  },
  {
    id: "S0000319", firstName: "Rafael",   lastName: "Santos",
    rank: "Third Officer", nationality: "Brazilian", status: "Onboard",
    dateOfBirth: "11 Mar 1994", placeOfBirth: "Rio de Janeiro, Brazil",
    vesselType: "Tanker", lastVessel: "Suezmax Liberty", currentVessel: "Nordic Ruth",
    availableFrom: "01 Jan 2027", assignmentDate: "01 Jul 2026", agent: "Nordic Tankers Manning",
    phone: "+55 21 99876 5432",
    airport: "GIG — Rio de Janeiro Galeão", salary: 4100, age: 31, promotions: 1, performanceScore: 83,
  },
  {
    id: "S0000320", firstName: "Amara",    lastName: "Diallo",
    rank: "AB Seaman", nationality: "Guinean", status: "Available",
    dateOfBirth: "29 Aug 1997", placeOfBirth: "Conakry, Guinea",
    vesselType: "General cargo", lastVessel: "African Pride",
    availableFrom: "15 Jun 2026", assignmentDate: "15 Jun 2026", agent: "Atlantic Manning",
    airport: "CKY — Conakry", salary: 1600, age: 28, promotions: 0, performanceScore: 75,
  },
  {
    id: "S0000321", firstName: "Olga",     lastName: "Fedorova",
    rank: "Second Officer", nationality: "Ukrainian", status: "Onboard",
    dateOfBirth: "17 Jun 1991", placeOfBirth: "Mykolaiv, Ukraine",
    vesselType: "Bulk carrier", lastVessel: "Thalassa Avra", currentVessel: "Thalassa Hellas",
    availableFrom: "15 Feb 2027", assignmentDate: "15 Aug 2026", agent: "Marlow Navigation",
    email: "o.fedorova@example.com",
    airport: "NLV — Mykolaiv", salary: 5200, age: 34, promotions: 2, performanceScore: 88,
  },
];
